---
VIRBL:
  127.0.0.2: malware or phishing email sources
SPAMHAUS:
  127.0.0.3: Illegal 3rd party exploits, including proxies, worms and trojan exploits
  127.0.0.4: Illegal 3rd party exploits, including proxies, worms and trojan exploits
  127.0.0.5: Illegal 3rd party exploits, including proxies, worms and trojan exploits
  127.0.0.6: Illegal 3rd party exploits, including proxies, worms and trojan exploits
  127.0.0.2: Direct UBE sources, verified spam services and ROKSO spammers
  127.0.0.10: ISP Maintained Policy Block List
  127.0.0.11: SpamHaus Maintained Policy Block List
URIBL:
  127.0.0.4: Address found in UBE/UCE, and probably honour opt-out requests
  127.0.0.8: Address not listed on black and are either very young (domain age via whois), or use whois privacy features to protect their identity.
  127.0.0.2: Address belonging to and used by spammers
SURBL:
  127.0.0.64: jwSpamSpy + Prolocation data source
  127.0.0.32: AbuseButler spamvertised sites
  127.0.0.4: sa-blacklist and other sources
  127.0.0.8: Phishing data source
  127.0.0.16: Outblaze spamvertised sites
  127.0.0.2: SpamCop message-body URI domains
NJABL:
  127.0.0.3: Dial-up/dynamic IP range
  127.0.0.4: Spam source
  127.0.0.5: Multi-stage open relays
  127.0.0.8: Insecure CGI web server, possible spam source
  127.0.0.9: Open proxy servers
  127.0.0.2: Open relay
SPAMCOP:
  "0": OK
  127.0.0.2: Spam source
SORBS:
  127.0.0.3: Open SOCKS Proxy Servers
  127.0.0.10: Dial Up Users
  127.0.0.11: domain names where the A or MX records point to bad address space
  127.0.0.4: Misc Open Proxy Servers
  127.0.0.12: domain names where the owners have indicated no mail should ever be sent with these domains
  127.0.0.5: Open SMTP Relays
  127.0.0.6: Spam Sources
  127.0.0.7: web (WWW) server which have spammer abused vulnerabilities (e.g. FormMail scripts)
  "0": OK
  127.0.0.8: hosts demanding they are never tested by SORBS
  127.0.0.9: Botnet/DDoS Zombies
  127.0.0.2: Open HTTP Proxy Servers
AHBL:
  127.0.0.20: Blog/Wiki/Comment Spammer
  127.0.0.3: Open Proxy
  127.0.0.10: Shoot On Sight
  127.0.0.11: Non-RFC Compliant (missing postmaster or abuse)
  127.0.0.4: Spam Source
  127.0.0.12: Does not properly handle 5xx errors
  127.0.0.5: Provisional Spam Source Listing block (will be removed if spam stops)
  127.0.0.127: Other
  127.0.0.13: Other Non-RFC Compliant
  127.0.0.6: Formmail Spam
  127.0.0.14: Compromised System => DDoS
  127.0.0.7: Spam Supporter
  "0": OK
  127.0.0.15: Compromised System => Relay
  127.0.0.8: Spam Supporter (indirect)
  127.0.0.16: Compromised System => Autorooter/Scanner
  127.0.0.9: End User (non mail system)
  127.0.0.17: Compromised System => Worm or mass mailing virus
  127.0.0.18: Compromised System => Other virus
  127.0.0.19: Open Proxy
  127.0.0.2: Open Relay
DRONEBL:
  "0": OK
  127.0.0.1: Host listed in DroneBL
  127.0.0.2: Sample
  127.0.0.3: IRC Drone
  127.0.0.5: Bottler
  127.0.0.6: Unknown spambot or drone
  127.0.0.7: DDOS Drone
  127.0.0.8: SOCKS Proxy
  127.0.0.9: HTTP Proxy
  127.0.0.10: ProxyChain
  127.0.0.13: Brute force attackers
  127.0.0.14: Open Wingate Proxy
  127.0.0.15: Compromised router / gateway
  127.0.0.17: Automatically determined botnet IPs (experimental)
  127.0.0.255: Unknown
BARRACUDA:
  "0": OK
  127.0.0.2: Listed
DRONE_ABUSE_CH:
  "0": OK
  127.0.0.2: Spam related FastFlux Bot
  127.0.0.3: Malware related FastFlux Bot
  127.0.0.4: Phish related FastFlux Bot
  127.0.0.5: Scam related FastFlux Bot
HTTPBL_ABUSE_CH:
  "0": OK
  127.0.0.2: Hacking activities
  127.0.0.3: Hijacked server automated scanning drone
  127.0.0.4: Referrer spam
SPAM_ABUSE_CH:
  0: OK
  127.0.0.1: Sends spam to spamtrap
MAILSHELL:
  0: OK
  127.0.0.2: Blacklisted
  127.0.0.188: Blacklisted
  127.0.0.190: Blacklisted
CBL:
  0: OK
  127.0.0.2: Blacklisted
RHSBL:
  0: OK
  127.0.0.2: Blacklisted
FIVETENSG:
  127.0.0.2: Spam
  127.0.0.3: Dialup
  127.0.0.4: Bulk
  127.0.0.5: Multistage
  127.0.0.6: Singlestage
  127.0.0.7: Spam-support
  127.0.0.8: Webform
  127.0.0.9: Misc
  127.0.0.10: klez
  127.0.0.11: tcpa
  127.0.0.12: free
  127.0.0.13: cr
INPS:
  127.0.0.2: Blacklisted
MANITU:
  127.0.0.2: Blacklisted
NOMOREFUN:
  127.0.0.2: Direct spam sources
  127.0.0.3: Dynamic IP or generic rDNS.
  127.0.0.4: Bulk mailers
  127.0.0.5: Multi stage open relay
  127.0.0.6: single stage open relay
  127.0.0.7: Ignoring complaints of spamming by customers
  127.0.0.8: Please update your formmail.pl script
  127.0.0.9: See http://moensted.dk/spam/no-more-funn/?addr=$
  127.0.0.10: Possible open proxy
  127.0.0.11: Please stop testing our servers
SPAMCANNIBAL:
  127.0.0.2: Blacklisted
UCEPROTECT1:
  127.0.0.2: Blacklisted
UCEPROTECT2:
  127.0.0.2: Blacklisted
UCEPROTECT3:
  127.0.0.2: Blacklisted
WHITELIST:
  127.0.0.2: Whitelisted
BACKSCATTERER:
  127.0.0.2: Backscatterer
PROJECTHONEYPOT:
TOREXITNODE:
  127.0.0.100: Tor Exit Node
  
